# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: 745eface02aef23e168a8afb6b5737818efbea95  # frozen: v0.11.0.1
  hooks:
  - id: shellcheck
    exclude: examples/|testing/tests/.*\.sh

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: 85cc16bc0319e182d7b62b0a2de351358083ce4c  # frozen: v4.0.0
  hooks:
  - id: shfmt
    exclude: examples/t6.sh
    args: ["-w", "-i", "4", "-ci"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
    exclude: ^testing/Baseline
  - id: end-of-file-fixer
    exclude: ^testing/Baseline|examples/.*Baseline.*

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 77039ccbba72c8aede339c5f8ae29b42aced0a2e  # frozen: v0.15.18
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

exclude: examples/sphinx/conf.py
